version: "2"
services:
  nc-project:
    container_name: nc-project
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: mysql
    image: mysql
    environment: 
      MYSQL_DATABASE: 'shop'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"